refactor: optimize

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,67 +1,64 @@
 #!/bin/sh
+trap catch ERR
+trap finish EXIT
 
-cat <<EOF
+# Functions
+mes() {
+    printf "\e[32mInstalling: \e[m$1\n"
+}
+finish() {
+    printf "\n\e[1;37;42m Done \e[m\n\n"
+}
+catch() {
+    printf "\e[1;37;41m Error \e[m\n"
+}
 
---------------------------------------------------------------------------------
-  dotfiles install: symlinks
---------------------------------------------------------------------------------
-
-Installing symlinks...
-
-EOF
+# Installer ----------------------------------------------------------------------
 
 # bash
-echo "bash"
+mes "bash"
 ln -sf ~/dotfiles/.bashrc ~/.bashrc
 
 # zsh
-echo "zsh"
+mes "zsh"
 ln -sf ~/dotfiles/.zprofile ~/.zprofile
 ln -sf ~/dotfiles/.zshrc ~/.zshrc
 ln -sf ~/dotfiles/.p10k.zsh ~/.p10k.zsh
 
 # fish
-echo "fish"
+mes "fish"
 ln -sf ~/dotfiles/.config/fish/ ~/.config
 
 # tmux
-echo "tmux"
+mes "tmux"
 ln -sf ~/dotfiles/.tmux.conf ~/.tmux.conf
 ln -sf ~/dotfiles/.tmux.conf.darwin ~/.tmux.conf.darwin
 ln -sf ~/dotfiles/.tmux.powerline.conf ~/.tmux.powerline.conf
 
 # Starship
-echo "Starship"
+mes "Starship"
 ln -sf ~/dotfiles/.config/starship.toml ~/.config
 
 # Neovim
-echo "Neovim"
+mes "Neovim"
 ln -sf ~/dotfiles/.config/nvim/ ~/.config
 
 # Helix
-echo "Helix"
+mes "Helix"
 ln -sf ~/dotfiles/.config/helix/ ~/.config
 
 # Kakoune
-echo "Kakoune"
+mes "Kakoune"
 ln -sf ~/dotfiles/.config/kak/ ~/.config
 
 # MongoDB Shell
-echo "MongoDB Shell"
+mes "MongoDB Shell"
 ln -sf ~/dotfiles/.mongoshrc.js ~/.mongoshrc.js
 
 # Hyper
-echo "Hyper"
+mes "Hyper"
 ln -sf ~/dotfiles/.hyper.js ~/.hyper.js
 
 # npm
-echo "npm"
+mes "npm"
 ln -sf ~/dotfiles/.npmrc ~/.npmrc
-
-cat <<EOF
-
---------------------------------------------------------------------------------
-  dotfiles install: done!!
---------------------------------------------------------------------------------
-
-EOF
