feat: uninstall action

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -3,6 +3,8 @@
 trap _ERROR ERR
 trap _FINISH EXIT
 
+ACTION=$1
+
 INSTALLING_FILE=""
 ERROR_COUNT=0
 
@@ -12,9 +14,10 @@ INSTALL() {
 }
 
 _FINISH() {
-    printf "\n\e[1;37;42m Done \e[m\n\n"
     if [ $ERROR_COUNT -gt 0 ]; then
-        printf "\e[1;37;41m $ERROR_COUNT errors \e[m\n\n"
+        printf "\n\e[1;37;41m $ERROR_COUNT errors \e[m\n\n"
+    else
+        printf "\n\e[1;37;42m Done \e[m\n\n"
     fi
 }
 
@@ -23,76 +26,118 @@ _ERROR() {
     ERROR_COUNT=$((ERROR_COUNT+1))
 }
 
-mkdir -p ~/.config
-
-INSTALL hammerspoon
-ln -snf ~/dotfiles/.hammerspoon ~/
-
-INSTALL kitty
-ln -snf ~/dotfiles/.config/kitty ~/.config/
-
-INSTALL bash
-ln -snf ~/dotfiles/.bashrc ~/.bashrc
-
-INSTALL zsh
-ln -snf ~/dotfiles/.zprofile ~/.zprofile
-ln -snf ~/dotfiles/.zshrc ~/.zshrc
-
-INSTALL fish
-ln -snf ~/dotfiles/.config/fish ~/.config/
-
-INSTALL yabai
-ln -snf ~/dotfiles/.config/yabai ~/.config/
-
-INSTALL skhd
-ln -snf ~/dotfiles/.config/skhd ~/.config/
-
-INSTALL simple-bar
-ln -snf ~/dotfiles/.simplebarrc ~/.simplebarrc
-
-INSTALL ranger
-ln -snf ~/dotfiles/.config/ranger ~/.config/
-
-INSTALL tmux
-ln -snf ~/dotfiles/.tmux.conf ~/.tmux.conf
-ln -snf ~/dotfiles/.tmux.darwin.conf ~/.tmux.darwin.conf
-ln -snf ~/dotfiles/.tmux.powerline.conf ~/.tmux.powerline.conf
-
-INSTALL Starship
-ln -snf ~/dotfiles/.config/starship.toml ~/.config/starship.toml
-
-INSTALL Git
-ln -snf ~/dotfiles/.config/git ~/.config/
-
-INSTALL Emacs
-# ln -snf ~/dotfiles/.emacs.d/ ~/.emacs.d
-# Use Spacemacs instead of above (check if .emacs.d exists)
-if [ ! -d ~/.emacs.d ]; then
-    git clone https://github.com/syl20bnr/spacemacs $HOME/.emacs.d
+if [ $# -eq 0 ]; then
+    printf "\e[1;37;41m Error \e[m No action specified\n"
+    ERROR_COUNT=$((ERROR_COUNT+1))
+    exit 1
 fi
-ln -snf ~/dotfiles/.spacemacs.d/ ~/.spacemacs.d
 
-INSTALL nano
-ln -snf ~/dotfiles/.config/nano ~/.config/
+case $ACTION in
+    "install")
+        mkdir -p ~/.config
 
-INSTALL Vim
-ln -snf ~/dotfiles/.vimrc ~/.vimrc
+        INSTALL hammerspoon
+        ln -snf ~/dotfiles/.hammerspoon ~/
 
-INSTALL Neovim
-ln -snf ~/dotfiles/.config/nvim ~/.config/
+        INSTALL kitty
+        ln -snf ~/dotfiles/.config/kitty ~/.config/
 
-INSTALL Helix
-ln -snf ~/dotfiles/.config/helix ~/.config/
+        INSTALL bash
+        ln -snf ~/dotfiles/.bashrc ~/.bashrc
 
-INSTALL Kakoune
-ln -snf ~/dotfiles/.config/kak ~/.config/
+        INSTALL zsh
+        ln -snf ~/dotfiles/.zprofile ~/.zprofile
+        ln -snf ~/dotfiles/.zshrc ~/.zshrc
 
-INSTALL MongoDB Shell
-ln -snf ~/dotfiles/.mongoshrc.js ~/.mongoshrc.js
+        INSTALL fish
+        ln -snf ~/dotfiles/.config/fish ~/.config/
 
-INSTALL PowerShell
-mkdir -p ~/.config/powershell
-ln -snf ~/dotfiles/.config/powershell/linux.ps1 ~/.config/powershell/Microsoft.PowerShell_profile.ps1
+        INSTALL yabai
+        ln -snf ~/dotfiles/.config/yabai ~/.config/
 
-INSTALL Hyper
-ln -snf ~/dotfiles/.hyper.js ~/.hyper.js
+        INSTALL skhd
+        ln -snf ~/dotfiles/.config/skhd ~/.config/
+
+        INSTALL simple-bar
+        ln -snf ~/dotfiles/.simplebarrc ~/.simplebarrc
+
+        INSTALL ranger
+        ln -snf ~/dotfiles/.config/ranger ~/.config/
+
+        INSTALL tmux
+        ln -snf ~/dotfiles/.tmux.conf ~/.tmux.conf
+        ln -snf ~/dotfiles/.tmux.darwin.conf ~/.tmux.darwin.conf
+        ln -snf ~/dotfiles/.tmux.powerline.conf ~/.tmux.powerline.conf
+
+        INSTALL Starship
+        ln -snf ~/dotfiles/.config/starship.toml ~/.config/starship.toml
+
+        INSTALL Git
+        ln -snf ~/dotfiles/.config/git ~/.config/
+
+        INSTALL Emacs
+        # ln -snf ~/dotfiles/.emacs.d/ ~/.emacs.d
+        # Use Spacemacs instead of above (check if .emacs.d exists)
+        if [ ! -d ~/.emacs.d ]; then
+            git clone https://github.com/syl20bnr/spacemacs $HOME/.emacs.d
+        fi
+        ln -snf ~/dotfiles/.spacemacs.d/ ~/.spacemacs.d
+
+        INSTALL nano
+        ln -snf ~/dotfiles/.config/nano ~/.config/
+
+        INSTALL Vim
+        ln -snf ~/dotfiles/.vimrc ~/.vimrc
+
+        INSTALL Neovim
+        ln -snf ~/dotfiles/.config/nvim ~/.config/
+
+        INSTALL Helix
+        ln -snf ~/dotfiles/.config/helix ~/.config/
+
+        INSTALL Kakoune
+        ln -snf ~/dotfiles/.config/kak ~/.config/
+
+        INSTALL MongoDB Shell
+        ln -snf ~/dotfiles/.mongoshrc.js ~/.mongoshrc.js
+
+        INSTALL PowerShell
+        mkdir -p ~/.config/powershell
+        ln -snf ~/dotfiles/.config/powershell/linux.ps1 ~/.config/powershell/Microsoft.PowerShell_profile.ps1
+
+        INSTALL Hyper
+        ln -snf ~/dotfiles/.hyper.js ~/.hyper.js
+        ;;
+    "uninstall")
+        unlink ~/.hammerspoon
+        unlink ~/.config/kitty
+        unlink ~/.bashrc
+        unlink ~/.zprofile
+        unlink ~/.zshrc
+        unlink ~/.config/fish
+        unlink ~/.config/yabai
+        unlink ~/.config/skhd
+        unlink ~/.simplebarrc
+        unlink ~/.config/ranger
+        unlink ~/.tmux.conf
+        unlink ~/.tmux.darwin.conf
+        unlink ~/.tmux.powerline.conf
+        unlink ~/.config/starship.toml
+        unlink ~/.config/git
+        unlink ~/.emacs.d
+        unlink ~/.spacemacs.d
+        unlink ~/.config/nano
+        unlink ~/.vimrc
+        unlink ~/.config/nvim
+        unlink ~/.config/helix
+        unlink ~/.config/kak
+        unlink ~/.mongoshrc.js
+        unlink ~/.config/powershell/Microsoft.PowerShell_profile.ps1
+        unlink ~/.hyper.js
+        ;;
+    *)
+        printf "\e[1;37;41m Error \e[m Unknown action: $ACTION\n"
+        ERROR_COUNT=$((ERROR_COUNT+1))
+        exit 1
+        ;;
+esac
